#!/bin/bash

#set -eEu
#set -o pipefail


createNewSession() {
	ttyl clean &>/dev/null
	MAX_ARGS=4

	echo 'Are you using a config file for this session [Y/n]?'
	read configFile

	if [[ "$configFile" =~ (y|yes) || -z $configFile ]]; then
		echo "What is the name of the config file? [Press ENTER for 'default']"
		read configName
		
		if [ -z $configName ]
		then
			configName=default
		fi

		procs=()

		while IFS= read -r line
		do
			procs+=("$line")
		done < $HOME/.ttyl/$configName
		
		sessionName=$configName

	else
		echo 'Which processes would you like to run [e.g. ranger mutt bash]?'
		read procs
		readarray -d ' ' procs <<<"$procs"

		echo 'What would you like to name your session?'
		read sessionName

		if [[ -z "$sessionName" ]]; then
			sessionName=ttyl
		fi
	fi


	arrSize=${#procs[@]}
	let discrep=$MAX_ARGS-$arrSize

	if [[ $discrep -ne 0 ]]; then
		for i in $discrep + 1
		do
			procs+=('')
		done
	fi

	echo "[+] Initializing _ttylemetry..."
	./_ttylemetry $sessionName ${procs[0]} ${procs[1]} ${procs[2]} ${procs[3]}
	exit 0
}


main() {
	clear
	echo ''
	echo 'Welcome to...'
	echo '		░▀█▀░▀█▀░█░█░█░░░█▀▀░█▄█░█▀▀░▀█▀░█▀▄░█░█
		░░█░░░█░░░█░░█░░░█▀▀░█░█░█▀▀░░█░░█▀▄░░█░
	   	░░▀░░░▀░░░▀░░▀▀▀░▀▀▀░▀░▀░▀▀▀░░▀░░▀░▀░░▀░'
	echo ''
	echo 'What kind of session would you like to start?'
	echo '(n|new) New session'
	echo '(a|active) Active/existing session'
	echo '(q|quit) Quit'
	read sessionType
	
	case $sessionType in
	
		n|new)
			createNewSession
			;;
	
		a|active)
			echo "What is the session name?"
			read sessionName
			tmux attach-session -t $sessionName
			;;
		
		q|quit)
			echo "Goodbye!"
			exit 0
			;;

		*)
			main
			;;
	esac
}


if [[ $# -eq 0 ]]; then
	main
else	
	if [[ $1 == clean ]]; then
		tmux kill-session
		exit 0
	fi
fi
